In [13]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt 
import seaborn as sns
%matplotlib inline

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

In [9]:
import joblib

In [14]:
from sklearn.datasets import load_boston

boston = load_boston()
df= pd.DataFrame(boston.data, columns= boston.feature_names)
df['price'] = boston.target
df.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3  0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4  0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   

   PTRATIO       B  LSTAT  price  
0     15.3  396.90   4.98   24.0  
1     17.8  396.90   9.14   21.6  
2     17.8  392.83   4.03   34.7  
3     18.7  394.63   2.94   33.4  
4     18.7  396.90   5.33   36.2

In [ ]:
#그래프
        fig, asx = plt.subplots(figsize=(16,8), ncols=4, nrows=2)
        feature_names = ['RM','ZN','INDUS','NOX','AGE','PTRATIO','LSTAT','RAD']
        for i, feature in enumerate(feature_name):
            row, col = int(i/4), i%4
            sns.regplot(x=feature, y='price', data=df, ax=asx[row][col])

In [15]:
X_train,X_test,y_train, y_test = train_test_split(df,boston.target,test_size=0.3, random_state=100)
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((354, 14), (152, 14), (354,), (152,))

In [42]:
df.to_csv('../static/data/boston.csv',sep=',',encoding='utf8',index=False)


In [54]:
X_train.to_csv('../static/data/boston_train1.csv',sep=',',encoding='utf8',index=False)
X_test.to_csv('../static/data/boston_test1.csv',sep=',',encoding='utf8',index=False)

In [23]:
#선형 회귀분석
lr= LinearRegression()
lr.fit(X_train,y_train)
pred_lr= lr.predict(X_test)
Weight=lr.coef_
bias = lr.intercept_

mse = mean_squared_error(y_test, pred)
r2= r2_score(y_test,pred)
print(f'MSE: {mse:.2f}, RMSE: {np.sqrt(mse):.2f}')
print(f'R_squared: {r2:.4f}')

MSE: 0.00, RMSE: 0.00
R_squared: 1.0000


In [ ]:
#선형 회귀분석
lr= LinearRegression()
lr.fit(X_train,y_train)
pred_lr= lr.predict(X_test.reshape(1,-1))
Weight=lr.coef_
bias = lr.intercept_

mse = mean_squared_error(y_test, pred)
r2= r2_score(y_test,pred)
print(f'MSE: {mse:.2f}, RMSE: {np.sqrt(mse):.2f}')
print(f'R_squared: {r2:.4f}')

In [17]:
Weight,bias

(array([-8.85034380e-17,  4.16333634e-17,  2.38632898e-16,  1.25986402e-14,
         2.14709571e-14,  8.94304162e-16,  4.08527379e-16,  2.11549528e-15,
        -4.16984156e-16, -8.32667268e-17,  1.58919644e-15, -2.37657116e-16,
         7.48099499e-16,  1.00000000e+00]),
 7.105427357601002e-15)

In [18]:
#회귀식
#PRICE = -8.85CRIM + ZN + 0.034INDUS + 3.05CHAS - 0.198NOX + 3.35RM + 0.006AGE - 1.74DIS + 0.356RAD - 0.014TAX - 0.92PTRATIO + 0.01B - 0.566*LSTA

In [19]:
#KNN 회귀분석
from sklearn.neighbors import KNeighborsRegressor
knn_model = KNeighborsRegressor()
knn_model.fit(X_train,y_train)

KNeighborsRegressor()

In [20]:
pred_knn=knn_model.predict(X_test)

In [25]:
for i in range(10):
    print("실제값 : {} ==> 예측값 : {}".format(y_test[i],pred[i]))

실제값 : 34.6 ==> 예측값 : 34.59999999999999
실제값 : 31.5 ==> 예측값 : 31.499999999999982
실제값 : 20.6 ==> 예측값 : 20.600000000000005
실제값 : 14.5 ==> 예측값 : 14.500000000000014
실제값 : 16.2 ==> 예측값 : 16.199999999999996
실제값 : 22.3 ==> 예측값 : 22.300000000000015
실제값 : 22.8 ==> 예측값 : 22.79999999999999
실제값 : 24.4 ==> 예측값 : 24.399999999999995
실제값 : 19.8 ==> 예측값 : 19.800000000000004
실제값 : 16.7 ==> 예측값 : 16.699999999999992


In [59]:
r2_knn= r2_score(y_test,pred)
r2_knn

1.0

In [27]:
print(f'R2 Score :', knn_model.score(X_train,y_train))
print(f'R2 Score :', knn_model.score(X_test,y_test))

R2 Score : 0.8075537318672884
R2 Score : 0.6817323222167349


In [ ]:
joblib.dump(best_rf, '../static/model/iris_rf.pkl')

In [41]:
print(boston.DESCR)

.. _boston_dataset:

Boston house prices dataset
---------------------------

**Data Set Characteristics:**  

    :Number of Instances: 506 

    :Number of Attributes: 13 numeric/categorical predictive. Median Value (attribute 14) is usually the target.

    :Attribute Information (in order):
        - CRIM     per capita crime rate by town
        - ZN       proportion of residential land zoned for lots over 25,000 sq.ft.
        - INDUS    proportion of non-retail business acres per town
        - CHAS     Charles River dummy variable (= 1 if tract bounds river; 0 otherwise)
        - NOX      nitric oxides concentration (parts per 10 million)
        - RM       average number of rooms per dwelling
        - AGE      proportion of owner-occupied units built prior to 1940
        - DIS      weighted distances to five Boston employment centres
        - RAD      index of accessibility to radial highways
        - TAX      full-value property-tax rate per $10,000
        - PTRATIO  pu

In [28]:
df_train = pd.read_csv('../static/data/boston_train.csv')
df_test = pd.read_csv('../static/data/boston_test.csv')

In [29]:
df_train.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS   RAD    TAX  \
0  6.53876   0.0  18.10   1.0  0.631  7.016  97.5  1.2024  24.0  666.0   
1  0.01870  85.0   4.15   0.0  0.429  6.516  27.7  8.5353   4.0  351.0   
2  9.82349   0.0  18.10   0.0  0.671  6.794  98.8  1.3580  24.0  666.0   
3  8.98296   0.0  18.10   1.0  0.770  6.212  97.4  2.1222  24.0  666.0   
4  0.15445  25.0   5.13   0.0  0.453  6.145  29.2  7.8148   8.0  284.0   

   PTRATIO       B  LSTAT  target  
0     20.2  392.05   2.96    50.0  
1     17.9  392.43   6.36    23.1  
2     20.2  396.90  21.24    13.3  
3     20.2  377.73  17.60    17.8  
4     19.7  390.68   6.86    23.3

In [34]:
df_test.head()

CRIM   ZN  INDUS  CHAS    NOX     RM   AGE     DIS   RAD    TAX  \
0  0.17446  0.0  10.59   1.0  0.489  5.960  92.1  3.8771   4.0  277.0   
1  0.75026  0.0   8.14   0.0  0.538  5.924  94.1  4.3996   4.0  307.0   
2  0.09744  0.0   5.96   0.0  0.499  5.841  61.4  3.3779   5.0  279.0   
3  9.39063  0.0  18.10   0.0  0.740  5.627  93.9  1.8172  24.0  666.0   
4  1.46336  0.0  19.58   0.0  0.605  7.489  90.8  1.9709   5.0  403.0   

   PTRATIO       B  LSTAT  target  
0     18.6  393.25  17.27    21.7  
1     21.0  394.33  16.30    15.6  
2     19.2  377.56  11.41    20.0  
3     20.2  396.90  22.88    12.8  
4     14.7  374.43   1.73    50.0

In [32]:
df_train.shape

(379, 14)

In [33]:
df_test.shape

(127, 14)

In [55]:
df_train1 = pd.read_csv('../static/data/boston_train1.csv')
df_test1 = pd.read_csv('../static/data/boston_test1.csv')
df_test1.head()

CRIM    ZN  INDUS  CHAS    NOX     RM    AGE     DIS  RAD    TAX  \
0  0.03768  80.0   1.52   0.0  0.404  7.274   38.3  7.3090  2.0  329.0   
1  0.44178   0.0   6.20   0.0  0.504  6.552   21.4  3.3751  8.0  307.0   
2  0.04527   0.0  11.93   0.0  0.573  6.120   76.7  2.2875  1.0  273.0   
3  1.35472   0.0   8.14   0.0  0.538  6.072  100.0  4.1750  4.0  307.0   
4  0.25356   0.0   9.90   0.0  0.544  5.705   77.7  3.9450  4.0  304.0   

   PTRATIO       B  LSTAT  price  
0     12.6  392.20   6.62   34.6  
1     17.4  380.34   3.76   31.5  
2     21.0  396.90   9.08   20.6  
3     21.0  376.73  13.04   14.5  
4     18.4  396.42  11.50   16.2

In [56]:
df_train1.shape

(354, 14)

In [57]:
df_test1.shape

(152, 14)

In [35]:
#Test
index = 4
test_data = (df_test.iloc[index, :-1].values)
label = test_data.iloc[index, -1]

test_data,label

(array([  1.46336,   0.     ,  19.58   ,   0.     ,   0.605  ,   7.489  ,
         90.8    ,   1.9709 ,   5.     , 403.     ,  14.7    , 374.43   ,
          1.73   ]),
 50.0)

In [36]:
test_data = test_data.reshape(1,-1) #1차원 데이터는 predict를 할수 없다.그래서 reshape 함
test_data

array([[  1.46336,   0.     ,  19.58   ,   0.     ,   0.605  ,   7.489  ,
         90.8    ,   1.9709 ,   5.     , 403.     ,  14.7    , 374.43   ,
          1.73   ]])

In [ ]:
#joblib.dump(best_rf, '../static/model/iris_rf.pkl') new_scaler = joblib.load('../static/model/iris_scaler.pkl')

In [53]:
a=list(boston.feature_names)
a

['CRIM',
 'ZN',
 'INDUS',
 'CHAS',
 'NOX',
 'RM',
 'AGE',
 'DIS',
 'RAD',
 'TAX',
 'PTRATIO',
 'B',
 'LSTAT']

In [60]:
b=knn_model.fit(X_train,y_train)
print(b)


KNeighborsRegressor()


In [64]:
list(df.columns)

['CRIM',
 'ZN',
 'INDUS',
 'CHAS',
 'NOX',
 'RM',
 'AGE',
 'DIS',
 'RAD',
 'TAX',
 'PTRATIO',
 'B',
 'LSTAT',
 'price']